### ISSUE TITLE
Багрепорты

### ISSUE THREAD

**Issue by TonitaN** [pear2jam/formal-languages#1]
В ЛР2 проблемы с пересечением, см: `^(?=a*b)b$`. Результат NONE, хотя должен быть `^b$`.

**Comment by TonitaN** [comment]
По ЛР1-0: смотрим на модель:
```
sat
(
  (define-fun Md2d1 () Int
    0)
  (define-fun Md2 () Int
    2)
  (define-fun IsLast_d1 () Int
    0)
  (define-fun Md2d2 () Int
    1)
  (define-fun Md1d2 () Int
    1)
  (define-fun Md0d2 () Int
    0)
  (define-fun Md0 () Int
    1)
  (define-fun Md0d0 () Int
    1)
  (define-fun Md2d0 () Int
    0)
  (define-fun IsLast_d2 () Int
    1)
  (define-fun IsLast_d0 () Int
    0)
  (define-fun Md1 () Int
    1)
  (define-fun Md1d1 () Int
    0)
  (define-fun Md0d1 () Int
    0)
  (define-fun Md1d0 () Int
    0)
)
```
В ней есть как минимум одна логическая проблема (возможно, две), которые нужно исправить.

**Comment by ArkadiyShevyrov** [comment]
По ЛР1-0:

Вероятно, дело в Md0d0 = 1 и Md0 = 1.

Поскольку, Md0d0 = 1 означает, что количество вхождений "домино 0" в "домино 0" = 1, следовательно у нас есть 2 "домино 0", следовательно Md0 = 2.

Ну и так же, если Md0d0 = 1, а Md0d1 и Md0d2 = 0, то это значит, что у нас "домино 0" никак не соприкасается с "домино 1" и "домино 2", что не может быть.

Вероятно нужно добавить условие, что-то типо такого:
Пусть есть dNdK=M и M!=0, если N=K, то домино с номером N как минимум M+1.
Если N!=K, то домино с номером N и домино с номером K, как минимум M штук.

**Comment by TonitaN** [comment]
Может быть `Md0d0=1` (правда, конечно, при этом `Md0=2`) и при этом `0` не соприкасается ни с чем другим. Как именно? Что тут не учтено?

**Comment by ArkadiyShevyrov** [comment]
Нашёл тест который как раз это показывает.

(a,a)
(b,b)
(d,c)

Он отдаёт ответ SATISFIABLE. Что быть не должно.

Вероятно это как раз связано с тем, что не проверяется, что домино обязательно должны соприкасаться друг с другом.
Осталось придумаю как написать это условие)

**Comment by TonitaN** [comment]
Тут-то как раз SAT корректен: достаточно не брать последнюю домино в комплект (должна быть использована хотя бы одна из набора, но не по одной каждого вида).
Но смычка 0+0 без соседства с другими домино и вправду может быть, если две нулевые домино - первая и последняя. Толку от такой комбинации для решения проблемы Поста никакого, но сам факт её существования отрицать нельзя. Поэтому модель должна учитывать ещё и первую домино.

**Comment by TonitaN** [comment]
На заглавном тесте в ЛР2 вылетает ошибка 
```
Traceback (most recent call last):
  File "D:\MSTU\FormalLangTheory\2023\Naumov\formal-languages\lab2\main.py", line 222, in <module>
    print('^' + norm_regex(regex_to_automata(parse_regex(r)).to_regex()) + '$')
  File "D:\MSTU\FormalLangTheory\2023\Naumov\formal-languages\lab2\main.py", line 144, in regex_to_automata
    aut = aut.concat(regex_to_automata(reg_tree.children[i]))
  File "D:\MSTU\FormalLangTheory\2023\Naumov\formal-languages\lab2\automata.py", line 167, in concat
    return self._concat(a)
  File "D:\MSTU\FormalLangTheory\2023\Naumov\formal-languages\lab2\automata.py", line 157, in _concat
    alphabet_new = alpha1.union(alpha2)
AttributeError: 'dict' object has no attribute 'union'
```

**Comment by TonitaN** [comment]
Какой-то дисбаланс в подсчётах:
```
  (define-fun Md0 () Int
    1)
...
  (define-fun MMd0d0 () Int
    1)
...
  (define-fun MMd1d0 () Int
    1)

```
Из-за того, что вы ввели два типа соседства (считая от начала и считая от конца) они оказались несогласованы по вертикали (т.е. могут быть ситуации, когда по типу соседства от начала одна доминошка имеет много соседей слева). У @ArkadiyShevyrov та же проблема, надо добавить вторые условия (что с поправкой на начальные и конечные домино, значения M и MM совпадают).

**Comment by ArkadiyShevyrov** [comment]
А разве условие, что Mdidj = MMdjdi не решает эту проблему?
```
 for (int i = 0; i < dominoes.size(); i++) {
            for (int j = 0; j < dominoes.size(); j++) {
                Term mdd = new ValueTerm("Md" + i + "d" + j);
                Term mmdd = new ValueTerm("MMd" + j + "d" + i);
                asserts.add(new Assert(
                        new EqualTerm(
                                mdd,
                                mmdd)));
            }
        }
```

**Comment by TonitaN** [comment]
Да, у вас в модели это условие есть, забыла...

**Comment by TonitaN** [comment]
Поскольку вы уже не первопроходец, прошу учесть также, что если домино определённого типа единственное, и оно одновременно конечное и начальное, то других домино уже быть не должно. Чтобы не получалось вот так:
```
  (define-fun MMd0d0 () Int
    0)
  (define-fun MMd0d1 () Int
    0)
  (define-fun MMd1d1 () Int
    2)
  (define-fun Md0 () Int
    1)
  (define-fun Md0d1 () Int
    0)
  (define-fun IsLast_d1 () Int
    0)
  (define-fun Md1 () Int
    2)
  (define-fun Md1d1 () Int
    2)
  (define-fun IsFirst_d0 () Int
    1)
  (define-fun Md0d0 () Int
    0)
  (define-fun MMd1d0 () Int
    0)
  (define-fun IsFirst_d1 () Int
    0)
  (define-fun IsLast_d0 () Int
    1)
  (define-fun Md1d0 () Int
    0)
```
И здесь опять соседство домино 1 дважды друг с другом по кругу, нужно добавить всё же, что соседств с собой не больше, чем число домино такого типа -1.

**Comment by TonitaN** [comment]
В ЛР2 опять проблемы с пересечением `^(?=a*b$)b*$` возвращает NONE, а должна `^b$`.

**Comment by TonitaN** [comment]
```
(assert (= Md0 (ite (or (and (= (* IsFirst_d1 IsLast_d1) 1) (= Md1 1))) 0 Md0) ))
```
Зачем тут OR? В остальном вопросов по этой лабораторной нет.

**Comment by TonitaN** [comment]
В ЛР2 теперь проблема с префиксными пересечениями...
```
^(?=a*b)b*$
```
Результат `^b$`, но должен быть типа `^bb*$`, поскольку данный lookahead накладывает ограничение только на префикс читаемого далее слова (т.к. выражение в нем не кончается `$`).

**Comment by TonitaN** [comment]
Если быстро исправите этот кейс, то можете приходить завтра на экзамен.

**Comment by pear2jam** [comment]
Можно пожалуйста подсказку, как с точки зрения формул с операциями над автоматами будет отличаться a1(?=a2$)a3 от a1(?=a2)a3. Т.е. как на формулу влияет $ в lookahead выражении?

**Comment by TonitaN** [comment]
Регулярка ниже преобразуется в `^ab$`, а должна в `^abb*$` (или эквивалентную)
```
^(?=(ab))(?=aa*)a*b*$
```
Ещё синтаксис lookbehind неточный, но уж это простим. А вот то, что пересечение считается неправильно, уже печально.

**Comment by TonitaN** [comment]
Продолжение приключений с пересечением:
```
^(?=(ab))(?=aa*)a*(<=(bb)*)b*$
```
Пересечение пусто.
Если поменять местами два lookahead-блока, то появятся регулярки, которые могут начинаться больше, чем с одной буквы a.

**Comment by TonitaN** [comment]
Даже без lookbehind видно, что проблемы ещё есть:
```
^(?=aa*)(?=(ab))a*b*$
```
В пересечении получается язык, принимающий слова `aba*`

**Comment by TonitaN** [comment]
Если доделаете без исправления логики lookbehind, всё равно зачту.

**Comment by TonitaN** [comment]
Всё зависает:
```
^(?=(a*b*)*)(aba)*$
```

**Comment by TonitaN** [comment]
C lookahead-ами всё неплохо, рада за вас. С ретроспективными проверками пока баги, но допуск есть!
